### ISSUE TITLE
Api giving urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by apidigger** [amosbastian/fpl#109]
Hi, 
I have been using FPL python package for last 3-4 months, since last week I'm getting this exception . I'm not sure am I the only one getting it?

for example:
Here is my simple API call:
from fpl import FPL
async def main():
    async with aiohttp.ClientSession() as session:
        **fpl = FPL(session)**
        print('getting players')
        players = await fpl.get_players(return_json=True)

Traceback (most recent call last):
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\http\client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\http\client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\http\client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\http\client.py", line 1012, in _send_output
    self.send(msg)
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\http\client.py", line 952, in send
    self.connect()
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\http\client.py", line 1426, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
**ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\apidigger\python\fpltweet\fplbasic.py", line 23, in <module>
    asyncio.run(main())
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\apidigger\python\fpltweet\fplbasic.py", line 10, in main
    fpl = FPL(session)
  File "C:\Users\apidigger\python\fpltweet\venv\lib\site-packages\fpl\fpl.py", line 50, in __init__
    static = json.loads(urlopen(API_URLS["static"]).read().decode("utf-8"))
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "c:\users\apidigger\appdata\local\programs\python\python39\lib\urllib\request.py", line 1349, in do_open
    **raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_**ssl.c:1129)>

Thanks
regards

**Comment by ChrisMusson** [comment]
#111 should have fixed it. When it has been merged, if you `pip install fpl --upgrade`, hopefully the error will have gone.
